name: check

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | sh -s -- -b ./bin
          echo "$PWD/bin" >> $GITHUB_PATH

      - name: Run checks
        run: task check
